# Generated by Django 4.2 on 2023-08-27 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(null=True, upload_to='item_images')),
                ('price', models.FloatField()),
                ('is_sold', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Books',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='item_images'),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='books',
            field=models.ForeignKey(default='DEFAULT_BOOK', on_delete=django.db.models.deletion.CASCADE, to='items.category'),
        ),
    ]
