# Generated by Django 4.2 on 2023-08-27 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_books_alter_category_options_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='books',
            field=models.ForeignKey(default='DEFAULT_BOOK', on_delete=django.db.models.deletion.CASCADE, to='items.books'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default='CATEGORY', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.category'),
        ),
    ]
