# Generated by Django 4.2 on 2023-08-27 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_books_alter_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('images', models.ImageField(null=True, upload_to='item_images')),
            ],
            options={
                'verbose_name_plural': 'Allcategories',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default='CATEGORY', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.allcategory'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
