# Generated by Django 4.2 on 2023-08-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_allcategory_alter_item_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcategory',
            name='images',
        ),
    ]
