# Generated by Django 4.2 on 2023-08-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_allcategory_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='image',
        ),
    ]
