# Generated by Django 4.2 on 2023-08-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_remove_books_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='item_images'),
        ),
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(null=True, upload_to='item_images'),
        ),
    ]
